services:
  - type: web
    name: college-path
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AUTH_TOKEN
        sync: false
